### PR TITLE
Add aarch64 and armhf

### PR DESCRIPTION
**Pull request by Lash-L**
Hello! You recently added armv7 for me. I am trying to use this package on home assistant, so I need support for a few more archs.

I hope this is okay!

### CODE REVIEW

**Comment by williamjacksn** [comment]
According to the QEMU output, available platforms are:

* linux/amd64
* linux/arm64
* linux/riscv64
* linux/ppc64le
* linux/s390x
* linux/386
* linux/mips64le
* linux/mips64
* linux/arm/v7
* linux/arm/v6

**Comment by Lash-L** [comment]
I can't see your message anymore - but I have been looking at it - and I'm not quite sure how to do it - i know Home Assistant creates containers for all of them, but I can't quite figure out how they do it.

Do you have any ideas or should I just close this and figure something else out?

**Comment by williamjacksn** [comment]
I’m working on it. I need to add these platforms to scipy before I can build scikit-learn.

**Comment by williamjacksn** [comment]
I have it working for aarch64, those wheels will be available for the next version (1.5.1).

When I tried to build for the platform `linux/armhf` it just reused the wheels for `linux/arm/v7`.

**Comment by williamjacksn** [comment]
Wheels for 1.5.1 are now published, including aarch64 platform.

**Pull request closed without merging**
